/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author Advan
 */
public class menuutama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuutama.class.getName());

    /**
     * Creates new form menuutama
     */
    public menuutama() {
        initComponents();
        System.out.println("Menu utama kebuka");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bpasien = new javax.swing.JButton();
        bdokter = new javax.swing.JButton();
        bdaftar = new javax.swing.JButton();
        bperiksa = new javax.swing.JButton();
        bresep = new javax.swing.JButton();
        bobat = new javax.swing.JButton();
        blogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Menu Utama");

        bpasien.setText("Pasien");
        bpasien.addActionListener(this::bpasienActionPerformed);

        bdokter.setText("Dokter");
        bdokter.addActionListener(this::bdokterActionPerformed);

        bdaftar.setText("Daftar");
        bdaftar.addActionListener(this::bdaftarActionPerformed);

        bperiksa.setText("Periksa");
        bperiksa.addActionListener(this::bperiksaActionPerformed);

        bresep.setText("Resep");
        bresep.addActionListener(this::bresepActionPerformed);

        bobat.setText("Obat");
        bobat.addActionListener(this::bobatActionPerformed);

        blogout.setText("Logout");
        blogout.addActionListener(this::blogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bperiksa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bresep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bobat, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bpasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdaftar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bperiksa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bresep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bobat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blogout)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftarActionPerformed
        new form_daftar().setVisible(true);
    }//GEN-LAST:event_bdaftarActionPerformed

    private void bobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobatActionPerformed
        new form_obat().setVisible(true);
    }//GEN-LAST:event_bobatActionPerformed

    private void bpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpasienActionPerformed
        new form_pasien().setVisible(true);
    }//GEN-LAST:event_bpasienActionPerformed

    private void bdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdokterActionPerformed
        new form_dokter().setVisible(true);
    }//GEN-LAST:event_bdokterActionPerformed

    private void bperiksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperiksaActionPerformed
        new form_periksa().setVisible(true);
    }//GEN-LAST:event_bperiksaActionPerformed

    private void bresepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresepActionPerformed
        new form_resep().setVisible(true);
    }//GEN-LAST:event_bresepActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        new form_login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_blogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuutama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdaftar;
    private javax.swing.JButton bdokter;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bobat;
    private javax.swing.JButton bpasien;
    private javax.swing.JButton bperiksa;
    private javax.swing.JButton bresep;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
